services:
  mongo:
    image: mongo
    container_name: practice-cloud-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app_back:
    build:
      context: CloudPractice
      dockerfile: Dockerfile 
    container_name: practice-cloud-back
    ports:
      - "8080:8080" 
    depends_on:
      - mongo

  app_front:
    build:
      context: CloudPracticeFront
      dockerfile: Dockerfile 
    container_name: practice-cloud-front
    ports:
      - "5000:80" 
    depends_on:
      - app_back

volumes:
  mongo_data:
